import anthropic

# Your funnel summary data from SQL Query 8
funnel_data = """
Stage           | Deals Entered | Deals Dropped | Conversion Rate
Lead            | 65            | 0             | 100.0%
Discovery Call  | 65            | 0             | 100.0%
Demo Booked     | 65            | 1             | 98.5%
Proposal Sent   | 64            | 14            | 78.1%
Negotiation     | 50            | 12            | 76.0%
"""

try:
    client = anthropic.Anthropic(api_key="API_KEY")

    message = client.messages.create(
        model="claude-sonnet-4-5",
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": f"""You are a Revenue Operations analyst at Novu Software, a B2B SaaS company.

Analyze the following sales funnel data and write a concise executive summary (3-4 paragraphs)
for the VP of Sales. Identify the biggest bottlenecks, explain what they mean for the business,
and recommend specific actions leadership should take.

Funnel Data:
{funnel_data}

Write in plain English. Be direct and specific. No bullet points - use paragraphs only."""
            }
        ]
    )

    print("=" * 60)
    print("NOVU SOFTWARE - FUNNEL ATTRIBUTION INSIGHT SUMMARY")
    print("Generated by Claude API")
    print("=" * 60)
    print()
    print(message.content[0].text)

except Exception as e:
    print(f"Error: {e}")